// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conv_param.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "conv_param.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class XZY_ConvolutionParamDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<XZY_ConvolutionParam>
     _instance;
} _XZY_ConvolutionParam_default_instance_;

namespace protobuf_conv_5fparam_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_ConvolutionParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_ConvolutionParam, col_matrix_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_ConvolutionParam, kernel_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_ConvolutionParam, col_table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_ConvolutionParam, weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_ConvolutionParam, biases_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(XZY_ConvolutionParam)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_XZY_ConvolutionParam_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "conv_param.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::protobuf_size_2eproto::InitDefaults();
  _XZY_ConvolutionParam_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_XZY_ConvolutionParam_default_instance_);_XZY_ConvolutionParam_default_instance_._instance.get_mutable()->col_matrix_size_ = const_cast< ::XZY_Size*>(
      ::XZY_Size::internal_default_instance());
  _XZY_ConvolutionParam_default_instance_._instance.get_mutable()->kernel_size_ = const_cast< ::XZY_Size*>(
      ::XZY_Size::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020conv_param.proto\032\nsize.proto\"\215\001\n\024XZY_C"
      "onvolutionParam\022\"\n\017col_matrix_size\030\001 \001(\013"
      "2\t.XZY_Size\022\036\n\013kernel_size\030\002 \001(\0132\t.XZY_S"
      "ize\022\021\n\tcol_table\030\003 \003(\005\022\016\n\006weight\030\004 \003(\002\022\016"
      "\n\006biases\030\005 \003(\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 182);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "conv_param.proto", &protobuf_RegisterTypes);
  ::protobuf_size_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_conv_5fparam_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int XZY_ConvolutionParam::kColMatrixSizeFieldNumber;
const int XZY_ConvolutionParam::kKernelSizeFieldNumber;
const int XZY_ConvolutionParam::kColTableFieldNumber;
const int XZY_ConvolutionParam::kWeightFieldNumber;
const int XZY_ConvolutionParam::kBiasesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

XZY_ConvolutionParam::XZY_ConvolutionParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_conv_5fparam_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:XZY_ConvolutionParam)
}
XZY_ConvolutionParam::XZY_ConvolutionParam(const XZY_ConvolutionParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      col_table_(from.col_table_),
      weight_(from.weight_),
      biases_(from.biases_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_col_matrix_size()) {
    col_matrix_size_ = new ::XZY_Size(*from.col_matrix_size_);
  } else {
    col_matrix_size_ = NULL;
  }
  if (from.has_kernel_size()) {
    kernel_size_ = new ::XZY_Size(*from.kernel_size_);
  } else {
    kernel_size_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:XZY_ConvolutionParam)
}

void XZY_ConvolutionParam::SharedCtor() {
  ::memset(&col_matrix_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&kernel_size_) -
      reinterpret_cast<char*>(&col_matrix_size_)) + sizeof(kernel_size_));
  _cached_size_ = 0;
}

XZY_ConvolutionParam::~XZY_ConvolutionParam() {
  // @@protoc_insertion_point(destructor:XZY_ConvolutionParam)
  SharedDtor();
}

void XZY_ConvolutionParam::SharedDtor() {
  if (this != internal_default_instance()) delete col_matrix_size_;
  if (this != internal_default_instance()) delete kernel_size_;
}

void XZY_ConvolutionParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* XZY_ConvolutionParam::descriptor() {
  protobuf_conv_5fparam_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_conv_5fparam_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const XZY_ConvolutionParam& XZY_ConvolutionParam::default_instance() {
  protobuf_conv_5fparam_2eproto::InitDefaults();
  return *internal_default_instance();
}

XZY_ConvolutionParam* XZY_ConvolutionParam::New(::google::protobuf::Arena* arena) const {
  XZY_ConvolutionParam* n = new XZY_ConvolutionParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void XZY_ConvolutionParam::Clear() {
// @@protoc_insertion_point(message_clear_start:XZY_ConvolutionParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  col_table_.Clear();
  weight_.Clear();
  biases_.Clear();
  if (GetArenaNoVirtual() == NULL && col_matrix_size_ != NULL) {
    delete col_matrix_size_;
  }
  col_matrix_size_ = NULL;
  if (GetArenaNoVirtual() == NULL && kernel_size_ != NULL) {
    delete kernel_size_;
  }
  kernel_size_ = NULL;
  _internal_metadata_.Clear();
}

bool XZY_ConvolutionParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:XZY_ConvolutionParam)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .XZY_Size col_matrix_size = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_col_matrix_size()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .XZY_Size kernel_size = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_kernel_size()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 col_table = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_col_table())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_col_table())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float weight = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_weight())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 34u, input, this->mutable_weight())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float biases = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_biases())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 42u, input, this->mutable_biases())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:XZY_ConvolutionParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:XZY_ConvolutionParam)
  return false;
#undef DO_
}

void XZY_ConvolutionParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:XZY_ConvolutionParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .XZY_Size col_matrix_size = 1;
  if (this->has_col_matrix_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->col_matrix_size_, output);
  }

  // .XZY_Size kernel_size = 2;
  if (this->has_kernel_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->kernel_size_, output);
  }

  // repeated int32 col_table = 3;
  if (this->col_table_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _col_table_cached_byte_size_));
  }
  for (int i = 0, n = this->col_table_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->col_table(i), output);
  }

  // repeated float weight = 4;
  if (this->weight_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _weight_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->weight().data(), this->weight_size(), output);
  }

  // repeated float biases = 5;
  if (this->biases_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _biases_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->biases().data(), this->biases_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:XZY_ConvolutionParam)
}

::google::protobuf::uint8* XZY_ConvolutionParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:XZY_ConvolutionParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .XZY_Size col_matrix_size = 1;
  if (this->has_col_matrix_size()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->col_matrix_size_, deterministic, target);
  }

  // .XZY_Size kernel_size = 2;
  if (this->has_kernel_size()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->kernel_size_, deterministic, target);
  }

  // repeated int32 col_table = 3;
  if (this->col_table_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _col_table_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->col_table_, target);
  }

  // repeated float weight = 4;
  if (this->weight_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _weight_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->weight_, target);
  }

  // repeated float biases = 5;
  if (this->biases_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _biases_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->biases_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:XZY_ConvolutionParam)
  return target;
}

size_t XZY_ConvolutionParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:XZY_ConvolutionParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 col_table = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->col_table_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _col_table_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float weight = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->weight_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _weight_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float biases = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->biases_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _biases_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // .XZY_Size col_matrix_size = 1;
  if (this->has_col_matrix_size()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->col_matrix_size_);
  }

  // .XZY_Size kernel_size = 2;
  if (this->has_kernel_size()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->kernel_size_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void XZY_ConvolutionParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:XZY_ConvolutionParam)
  GOOGLE_DCHECK_NE(&from, this);
  const XZY_ConvolutionParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const XZY_ConvolutionParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:XZY_ConvolutionParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:XZY_ConvolutionParam)
    MergeFrom(*source);
  }
}

void XZY_ConvolutionParam::MergeFrom(const XZY_ConvolutionParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:XZY_ConvolutionParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  col_table_.MergeFrom(from.col_table_);
  weight_.MergeFrom(from.weight_);
  biases_.MergeFrom(from.biases_);
  if (from.has_col_matrix_size()) {
    mutable_col_matrix_size()->::XZY_Size::MergeFrom(from.col_matrix_size());
  }
  if (from.has_kernel_size()) {
    mutable_kernel_size()->::XZY_Size::MergeFrom(from.kernel_size());
  }
}

void XZY_ConvolutionParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:XZY_ConvolutionParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void XZY_ConvolutionParam::CopyFrom(const XZY_ConvolutionParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XZY_ConvolutionParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XZY_ConvolutionParam::IsInitialized() const {
  return true;
}

void XZY_ConvolutionParam::Swap(XZY_ConvolutionParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void XZY_ConvolutionParam::InternalSwap(XZY_ConvolutionParam* other) {
  using std::swap;
  col_table_.InternalSwap(&other->col_table_);
  weight_.InternalSwap(&other->weight_);
  biases_.InternalSwap(&other->biases_);
  swap(col_matrix_size_, other->col_matrix_size_);
  swap(kernel_size_, other->kernel_size_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata XZY_ConvolutionParam::GetMetadata() const {
  protobuf_conv_5fparam_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_conv_5fparam_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// XZY_ConvolutionParam

// .XZY_Size col_matrix_size = 1;
bool XZY_ConvolutionParam::has_col_matrix_size() const {
  return this != internal_default_instance() && col_matrix_size_ != NULL;
}
void XZY_ConvolutionParam::clear_col_matrix_size() {
  if (GetArenaNoVirtual() == NULL && col_matrix_size_ != NULL) delete col_matrix_size_;
  col_matrix_size_ = NULL;
}
const ::XZY_Size& XZY_ConvolutionParam::col_matrix_size() const {
  const ::XZY_Size* p = col_matrix_size_;
  // @@protoc_insertion_point(field_get:XZY_ConvolutionParam.col_matrix_size)
  return p != NULL ? *p : *reinterpret_cast<const ::XZY_Size*>(
      &::_XZY_Size_default_instance_);
}
::XZY_Size* XZY_ConvolutionParam::mutable_col_matrix_size() {
  
  if (col_matrix_size_ == NULL) {
    col_matrix_size_ = new ::XZY_Size;
  }
  // @@protoc_insertion_point(field_mutable:XZY_ConvolutionParam.col_matrix_size)
  return col_matrix_size_;
}
::XZY_Size* XZY_ConvolutionParam::release_col_matrix_size() {
  // @@protoc_insertion_point(field_release:XZY_ConvolutionParam.col_matrix_size)
  
  ::XZY_Size* temp = col_matrix_size_;
  col_matrix_size_ = NULL;
  return temp;
}
void XZY_ConvolutionParam::set_allocated_col_matrix_size(::XZY_Size* col_matrix_size) {
  delete col_matrix_size_;
  col_matrix_size_ = col_matrix_size;
  if (col_matrix_size) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:XZY_ConvolutionParam.col_matrix_size)
}

// .XZY_Size kernel_size = 2;
bool XZY_ConvolutionParam::has_kernel_size() const {
  return this != internal_default_instance() && kernel_size_ != NULL;
}
void XZY_ConvolutionParam::clear_kernel_size() {
  if (GetArenaNoVirtual() == NULL && kernel_size_ != NULL) delete kernel_size_;
  kernel_size_ = NULL;
}
const ::XZY_Size& XZY_ConvolutionParam::kernel_size() const {
  const ::XZY_Size* p = kernel_size_;
  // @@protoc_insertion_point(field_get:XZY_ConvolutionParam.kernel_size)
  return p != NULL ? *p : *reinterpret_cast<const ::XZY_Size*>(
      &::_XZY_Size_default_instance_);
}
::XZY_Size* XZY_ConvolutionParam::mutable_kernel_size() {
  
  if (kernel_size_ == NULL) {
    kernel_size_ = new ::XZY_Size;
  }
  // @@protoc_insertion_point(field_mutable:XZY_ConvolutionParam.kernel_size)
  return kernel_size_;
}
::XZY_Size* XZY_ConvolutionParam::release_kernel_size() {
  // @@protoc_insertion_point(field_release:XZY_ConvolutionParam.kernel_size)
  
  ::XZY_Size* temp = kernel_size_;
  kernel_size_ = NULL;
  return temp;
}
void XZY_ConvolutionParam::set_allocated_kernel_size(::XZY_Size* kernel_size) {
  delete kernel_size_;
  kernel_size_ = kernel_size;
  if (kernel_size) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:XZY_ConvolutionParam.kernel_size)
}

// repeated int32 col_table = 3;
int XZY_ConvolutionParam::col_table_size() const {
  return col_table_.size();
}
void XZY_ConvolutionParam::clear_col_table() {
  col_table_.Clear();
}
::google::protobuf::int32 XZY_ConvolutionParam::col_table(int index) const {
  // @@protoc_insertion_point(field_get:XZY_ConvolutionParam.col_table)
  return col_table_.Get(index);
}
void XZY_ConvolutionParam::set_col_table(int index, ::google::protobuf::int32 value) {
  col_table_.Set(index, value);
  // @@protoc_insertion_point(field_set:XZY_ConvolutionParam.col_table)
}
void XZY_ConvolutionParam::add_col_table(::google::protobuf::int32 value) {
  col_table_.Add(value);
  // @@protoc_insertion_point(field_add:XZY_ConvolutionParam.col_table)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
XZY_ConvolutionParam::col_table() const {
  // @@protoc_insertion_point(field_list:XZY_ConvolutionParam.col_table)
  return col_table_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
XZY_ConvolutionParam::mutable_col_table() {
  // @@protoc_insertion_point(field_mutable_list:XZY_ConvolutionParam.col_table)
  return &col_table_;
}

// repeated float weight = 4;
int XZY_ConvolutionParam::weight_size() const {
  return weight_.size();
}
void XZY_ConvolutionParam::clear_weight() {
  weight_.Clear();
}
float XZY_ConvolutionParam::weight(int index) const {
  // @@protoc_insertion_point(field_get:XZY_ConvolutionParam.weight)
  return weight_.Get(index);
}
void XZY_ConvolutionParam::set_weight(int index, float value) {
  weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:XZY_ConvolutionParam.weight)
}
void XZY_ConvolutionParam::add_weight(float value) {
  weight_.Add(value);
  // @@protoc_insertion_point(field_add:XZY_ConvolutionParam.weight)
}
const ::google::protobuf::RepeatedField< float >&
XZY_ConvolutionParam::weight() const {
  // @@protoc_insertion_point(field_list:XZY_ConvolutionParam.weight)
  return weight_;
}
::google::protobuf::RepeatedField< float >*
XZY_ConvolutionParam::mutable_weight() {
  // @@protoc_insertion_point(field_mutable_list:XZY_ConvolutionParam.weight)
  return &weight_;
}

// repeated float biases = 5;
int XZY_ConvolutionParam::biases_size() const {
  return biases_.size();
}
void XZY_ConvolutionParam::clear_biases() {
  biases_.Clear();
}
float XZY_ConvolutionParam::biases(int index) const {
  // @@protoc_insertion_point(field_get:XZY_ConvolutionParam.biases)
  return biases_.Get(index);
}
void XZY_ConvolutionParam::set_biases(int index, float value) {
  biases_.Set(index, value);
  // @@protoc_insertion_point(field_set:XZY_ConvolutionParam.biases)
}
void XZY_ConvolutionParam::add_biases(float value) {
  biases_.Add(value);
  // @@protoc_insertion_point(field_add:XZY_ConvolutionParam.biases)
}
const ::google::protobuf::RepeatedField< float >&
XZY_ConvolutionParam::biases() const {
  // @@protoc_insertion_point(field_list:XZY_ConvolutionParam.biases)
  return biases_;
}
::google::protobuf::RepeatedField< float >*
XZY_ConvolutionParam::mutable_biases() {
  // @@protoc_insertion_point(field_mutable_list:XZY_ConvolutionParam.biases)
  return &biases_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
