// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fully_connected_param.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "fully_connected_param.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class XZY_FullyConnectedParamDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<XZY_FullyConnectedParam>
     _instance;
} _XZY_FullyConnectedParam_default_instance_;

namespace protobuf_fully_5fconnected_5fparam_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_FullyConnectedParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_FullyConnectedParam, weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XZY_FullyConnectedParam, biases_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(XZY_FullyConnectedParam)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_XZY_FullyConnectedParam_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "fully_connected_param.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _XZY_FullyConnectedParam_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_XZY_FullyConnectedParam_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\033fully_connected_param.proto\"9\n\027XZY_Ful"
      "lyConnectedParam\022\016\n\006weight\030\003 \003(\002\022\016\n\006bias"
      "es\030\004 \003(\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 96);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fully_connected_param.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_fully_5fconnected_5fparam_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int XZY_FullyConnectedParam::kWeightFieldNumber;
const int XZY_FullyConnectedParam::kBiasesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

XZY_FullyConnectedParam::XZY_FullyConnectedParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_fully_5fconnected_5fparam_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:XZY_FullyConnectedParam)
}
XZY_FullyConnectedParam::XZY_FullyConnectedParam(const XZY_FullyConnectedParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      weight_(from.weight_),
      biases_(from.biases_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:XZY_FullyConnectedParam)
}

void XZY_FullyConnectedParam::SharedCtor() {
  _cached_size_ = 0;
}

XZY_FullyConnectedParam::~XZY_FullyConnectedParam() {
  // @@protoc_insertion_point(destructor:XZY_FullyConnectedParam)
  SharedDtor();
}

void XZY_FullyConnectedParam::SharedDtor() {
}

void XZY_FullyConnectedParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* XZY_FullyConnectedParam::descriptor() {
  protobuf_fully_5fconnected_5fparam_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_fully_5fconnected_5fparam_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const XZY_FullyConnectedParam& XZY_FullyConnectedParam::default_instance() {
  protobuf_fully_5fconnected_5fparam_2eproto::InitDefaults();
  return *internal_default_instance();
}

XZY_FullyConnectedParam* XZY_FullyConnectedParam::New(::google::protobuf::Arena* arena) const {
  XZY_FullyConnectedParam* n = new XZY_FullyConnectedParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void XZY_FullyConnectedParam::Clear() {
// @@protoc_insertion_point(message_clear_start:XZY_FullyConnectedParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  weight_.Clear();
  biases_.Clear();
  _internal_metadata_.Clear();
}

bool XZY_FullyConnectedParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:XZY_FullyConnectedParam)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float weight = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_weight())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 26u, input, this->mutable_weight())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float biases = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_biases())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 34u, input, this->mutable_biases())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:XZY_FullyConnectedParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:XZY_FullyConnectedParam)
  return false;
#undef DO_
}

void XZY_FullyConnectedParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:XZY_FullyConnectedParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float weight = 3;
  if (this->weight_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _weight_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->weight().data(), this->weight_size(), output);
  }

  // repeated float biases = 4;
  if (this->biases_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _biases_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->biases().data(), this->biases_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:XZY_FullyConnectedParam)
}

::google::protobuf::uint8* XZY_FullyConnectedParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:XZY_FullyConnectedParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float weight = 3;
  if (this->weight_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _weight_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->weight_, target);
  }

  // repeated float biases = 4;
  if (this->biases_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _biases_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->biases_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:XZY_FullyConnectedParam)
  return target;
}

size_t XZY_FullyConnectedParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:XZY_FullyConnectedParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float weight = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->weight_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _weight_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float biases = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->biases_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _biases_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void XZY_FullyConnectedParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:XZY_FullyConnectedParam)
  GOOGLE_DCHECK_NE(&from, this);
  const XZY_FullyConnectedParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const XZY_FullyConnectedParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:XZY_FullyConnectedParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:XZY_FullyConnectedParam)
    MergeFrom(*source);
  }
}

void XZY_FullyConnectedParam::MergeFrom(const XZY_FullyConnectedParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:XZY_FullyConnectedParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  weight_.MergeFrom(from.weight_);
  biases_.MergeFrom(from.biases_);
}

void XZY_FullyConnectedParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:XZY_FullyConnectedParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void XZY_FullyConnectedParam::CopyFrom(const XZY_FullyConnectedParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XZY_FullyConnectedParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XZY_FullyConnectedParam::IsInitialized() const {
  return true;
}

void XZY_FullyConnectedParam::Swap(XZY_FullyConnectedParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void XZY_FullyConnectedParam::InternalSwap(XZY_FullyConnectedParam* other) {
  using std::swap;
  weight_.InternalSwap(&other->weight_);
  biases_.InternalSwap(&other->biases_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata XZY_FullyConnectedParam::GetMetadata() const {
  protobuf_fully_5fconnected_5fparam_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_fully_5fconnected_5fparam_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// XZY_FullyConnectedParam

// repeated float weight = 3;
int XZY_FullyConnectedParam::weight_size() const {
  return weight_.size();
}
void XZY_FullyConnectedParam::clear_weight() {
  weight_.Clear();
}
float XZY_FullyConnectedParam::weight(int index) const {
  // @@protoc_insertion_point(field_get:XZY_FullyConnectedParam.weight)
  return weight_.Get(index);
}
void XZY_FullyConnectedParam::set_weight(int index, float value) {
  weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:XZY_FullyConnectedParam.weight)
}
void XZY_FullyConnectedParam::add_weight(float value) {
  weight_.Add(value);
  // @@protoc_insertion_point(field_add:XZY_FullyConnectedParam.weight)
}
const ::google::protobuf::RepeatedField< float >&
XZY_FullyConnectedParam::weight() const {
  // @@protoc_insertion_point(field_list:XZY_FullyConnectedParam.weight)
  return weight_;
}
::google::protobuf::RepeatedField< float >*
XZY_FullyConnectedParam::mutable_weight() {
  // @@protoc_insertion_point(field_mutable_list:XZY_FullyConnectedParam.weight)
  return &weight_;
}

// repeated float biases = 4;
int XZY_FullyConnectedParam::biases_size() const {
  return biases_.size();
}
void XZY_FullyConnectedParam::clear_biases() {
  biases_.Clear();
}
float XZY_FullyConnectedParam::biases(int index) const {
  // @@protoc_insertion_point(field_get:XZY_FullyConnectedParam.biases)
  return biases_.Get(index);
}
void XZY_FullyConnectedParam::set_biases(int index, float value) {
  biases_.Set(index, value);
  // @@protoc_insertion_point(field_set:XZY_FullyConnectedParam.biases)
}
void XZY_FullyConnectedParam::add_biases(float value) {
  biases_.Add(value);
  // @@protoc_insertion_point(field_add:XZY_FullyConnectedParam.biases)
}
const ::google::protobuf::RepeatedField< float >&
XZY_FullyConnectedParam::biases() const {
  // @@protoc_insertion_point(field_list:XZY_FullyConnectedParam.biases)
  return biases_;
}
::google::protobuf::RepeatedField< float >*
XZY_FullyConnectedParam::mutable_biases() {
  // @@protoc_insertion_point(field_mutable_list:XZY_FullyConnectedParam.biases)
  return &biases_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
