// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fully_connected_param.proto

#ifndef PROTOBUF_fully_5fconnected_5fparam_2eproto__INCLUDED
#define PROTOBUF_fully_5fconnected_5fparam_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class XZY_FullyConnectedParam;
class XZY_FullyConnectedParamDefaultTypeInternal;
extern XZY_FullyConnectedParamDefaultTypeInternal _XZY_FullyConnectedParam_default_instance_;

namespace protobuf_fully_5fconnected_5fparam_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_fully_5fconnected_5fparam_2eproto

// ===================================================================

class XZY_FullyConnectedParam : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XZY_FullyConnectedParam) */ {
 public:
  XZY_FullyConnectedParam();
  virtual ~XZY_FullyConnectedParam();

  XZY_FullyConnectedParam(const XZY_FullyConnectedParam& from);

  inline XZY_FullyConnectedParam& operator=(const XZY_FullyConnectedParam& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XZY_FullyConnectedParam(XZY_FullyConnectedParam&& from) noexcept
    : XZY_FullyConnectedParam() {
    *this = ::std::move(from);
  }

  inline XZY_FullyConnectedParam& operator=(XZY_FullyConnectedParam&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XZY_FullyConnectedParam& default_instance();

  static inline const XZY_FullyConnectedParam* internal_default_instance() {
    return reinterpret_cast<const XZY_FullyConnectedParam*>(
               &_XZY_FullyConnectedParam_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(XZY_FullyConnectedParam* other);
  friend void swap(XZY_FullyConnectedParam& a, XZY_FullyConnectedParam& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XZY_FullyConnectedParam* New() const PROTOBUF_FINAL { return New(NULL); }

  XZY_FullyConnectedParam* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XZY_FullyConnectedParam& from);
  void MergeFrom(const XZY_FullyConnectedParam& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XZY_FullyConnectedParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float weight = 3;
  int weight_size() const;
  void clear_weight();
  static const int kWeightFieldNumber = 3;
  float weight(int index) const;
  void set_weight(int index, float value);
  void add_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_weight();

  // repeated float biases = 4;
  int biases_size() const;
  void clear_biases();
  static const int kBiasesFieldNumber = 4;
  float biases(int index) const;
  void set_biases(int index, float value);
  void add_biases(float value);
  const ::google::protobuf::RepeatedField< float >&
      biases() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_biases();

  // @@protoc_insertion_point(class_scope:XZY_FullyConnectedParam)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > weight_;
  mutable int _weight_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > biases_;
  mutable int _biases_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_fully_5fconnected_5fparam_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XZY_FullyConnectedParam

// repeated float weight = 3;
inline int XZY_FullyConnectedParam::weight_size() const {
  return weight_.size();
}
inline void XZY_FullyConnectedParam::clear_weight() {
  weight_.Clear();
}
inline float XZY_FullyConnectedParam::weight(int index) const {
  // @@protoc_insertion_point(field_get:XZY_FullyConnectedParam.weight)
  return weight_.Get(index);
}
inline void XZY_FullyConnectedParam::set_weight(int index, float value) {
  weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:XZY_FullyConnectedParam.weight)
}
inline void XZY_FullyConnectedParam::add_weight(float value) {
  weight_.Add(value);
  // @@protoc_insertion_point(field_add:XZY_FullyConnectedParam.weight)
}
inline const ::google::protobuf::RepeatedField< float >&
XZY_FullyConnectedParam::weight() const {
  // @@protoc_insertion_point(field_list:XZY_FullyConnectedParam.weight)
  return weight_;
}
inline ::google::protobuf::RepeatedField< float >*
XZY_FullyConnectedParam::mutable_weight() {
  // @@protoc_insertion_point(field_mutable_list:XZY_FullyConnectedParam.weight)
  return &weight_;
}

// repeated float biases = 4;
inline int XZY_FullyConnectedParam::biases_size() const {
  return biases_.size();
}
inline void XZY_FullyConnectedParam::clear_biases() {
  biases_.Clear();
}
inline float XZY_FullyConnectedParam::biases(int index) const {
  // @@protoc_insertion_point(field_get:XZY_FullyConnectedParam.biases)
  return biases_.Get(index);
}
inline void XZY_FullyConnectedParam::set_biases(int index, float value) {
  biases_.Set(index, value);
  // @@protoc_insertion_point(field_set:XZY_FullyConnectedParam.biases)
}
inline void XZY_FullyConnectedParam::add_biases(float value) {
  biases_.Add(value);
  // @@protoc_insertion_point(field_add:XZY_FullyConnectedParam.biases)
}
inline const ::google::protobuf::RepeatedField< float >&
XZY_FullyConnectedParam::biases() const {
  // @@protoc_insertion_point(field_list:XZY_FullyConnectedParam.biases)
  return biases_;
}
inline ::google::protobuf::RepeatedField< float >*
XZY_FullyConnectedParam::mutable_biases() {
  // @@protoc_insertion_point(field_mutable_list:XZY_FullyConnectedParam.biases)
  return &biases_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_fully_5fconnected_5fparam_2eproto__INCLUDED
