// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

#ifndef PROTOBUF_network_2eproto__INCLUDED
#define PROTOBUF_network_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "node.pb.h"
// @@protoc_insertion_point(includes)
class XZY_Network;
class XZY_NetworkDefaultTypeInternal;
extern XZY_NetworkDefaultTypeInternal _XZY_Network_default_instance_;

namespace protobuf_network_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_network_2eproto

// ===================================================================

class XZY_Network : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XZY_Network) */ {
 public:
  XZY_Network();
  virtual ~XZY_Network();

  XZY_Network(const XZY_Network& from);

  inline XZY_Network& operator=(const XZY_Network& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XZY_Network(XZY_Network&& from) noexcept
    : XZY_Network() {
    *this = ::std::move(from);
  }

  inline XZY_Network& operator=(XZY_Network&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XZY_Network& default_instance();

  static inline const XZY_Network* internal_default_instance() {
    return reinterpret_cast<const XZY_Network*>(
               &_XZY_Network_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(XZY_Network* other);
  friend void swap(XZY_Network& a, XZY_Network& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XZY_Network* New() const PROTOBUF_FINAL { return New(NULL); }

  XZY_Network* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const XZY_Network& from);
  void MergeFrom(const XZY_Network& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(XZY_Network* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .XZY_Node operation_nodes = 2;
  int operation_nodes_size() const;
  void clear_operation_nodes();
  static const int kOperationNodesFieldNumber = 2;
  const ::XZY_Node& operation_nodes(int index) const;
  ::XZY_Node* mutable_operation_nodes(int index);
  ::XZY_Node* add_operation_nodes();
  ::google::protobuf::RepeatedPtrField< ::XZY_Node >*
      mutable_operation_nodes();
  const ::google::protobuf::RepeatedPtrField< ::XZY_Node >&
      operation_nodes() const;

  // @@protoc_insertion_point(class_scope:XZY_Network)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::XZY_Node > operation_nodes_;
  mutable int _cached_size_;
  friend struct protobuf_network_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XZY_Network

// repeated .XZY_Node operation_nodes = 2;
inline int XZY_Network::operation_nodes_size() const {
  return operation_nodes_.size();
}
inline void XZY_Network::clear_operation_nodes() {
  operation_nodes_.Clear();
}
inline const ::XZY_Node& XZY_Network::operation_nodes(int index) const {
  // @@protoc_insertion_point(field_get:XZY_Network.operation_nodes)
  return operation_nodes_.Get(index);
}
inline ::XZY_Node* XZY_Network::mutable_operation_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:XZY_Network.operation_nodes)
  return operation_nodes_.Mutable(index);
}
inline ::XZY_Node* XZY_Network::add_operation_nodes() {
  // @@protoc_insertion_point(field_add:XZY_Network.operation_nodes)
  return operation_nodes_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::XZY_Node >*
XZY_Network::mutable_operation_nodes() {
  // @@protoc_insertion_point(field_mutable_list:XZY_Network.operation_nodes)
  return &operation_nodes_;
}
inline const ::google::protobuf::RepeatedPtrField< ::XZY_Node >&
XZY_Network::operation_nodes() const {
  // @@protoc_insertion_point(field_list:XZY_Network.operation_nodes)
  return operation_nodes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_network_2eproto__INCLUDED
