# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: batch_norm_param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='batch_norm_param.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x62\x61tch_norm_param.proto\"\\\n\x1bXZY_BatchNormalizationParam\x12\x0c\n\x04mean\x18\x02 \x03(\x02\x12\x10\n\x08variance\x18\x03 \x03(\x02\x12\r\n\x05scale\x18\x04 \x03(\x02\x12\x0e\n\x06offset\x18\x05 \x03(\x02\x62\x06proto3')
)




_XZY_BATCHNORMALIZATIONPARAM = _descriptor.Descriptor(
  name='XZY_BatchNormalizationParam',
  full_name='XZY_BatchNormalizationParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='XZY_BatchNormalizationParam.mean', index=0,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variance', full_name='XZY_BatchNormalizationParam.variance', index=1,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='XZY_BatchNormalizationParam.scale', index=2,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='XZY_BatchNormalizationParam.offset', index=3,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['XZY_BatchNormalizationParam'] = _XZY_BATCHNORMALIZATIONPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XZY_BatchNormalizationParam = _reflection.GeneratedProtocolMessageType('XZY_BatchNormalizationParam', (_message.Message,), dict(
  DESCRIPTOR = _XZY_BATCHNORMALIZATIONPARAM,
  __module__ = 'batch_norm_param_pb2'
  # @@protoc_insertion_point(class_scope:XZY_BatchNormalizationParam)
  ))
_sym_db.RegisterMessage(XZY_BatchNormalizationParam)


# @@protoc_insertion_point(module_scope)
