# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fully_connected_param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fully_connected_param.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1b\x66ully_connected_param.proto\"9\n\x17XZY_FullyConnectedParam\x12\x0e\n\x06weight\x18\x03 \x03(\x02\x12\x0e\n\x06\x62iases\x18\x04 \x03(\x02\x62\x06proto3')
)




_XZY_FULLYCONNECTEDPARAM = _descriptor.Descriptor(
  name='XZY_FullyConnectedParam',
  full_name='XZY_FullyConnectedParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='XZY_FullyConnectedParam.weight', index=0,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='biases', full_name='XZY_FullyConnectedParam.biases', index=1,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['XZY_FullyConnectedParam'] = _XZY_FULLYCONNECTEDPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XZY_FullyConnectedParam = _reflection.GeneratedProtocolMessageType('XZY_FullyConnectedParam', (_message.Message,), dict(
  DESCRIPTOR = _XZY_FULLYCONNECTEDPARAM,
  __module__ = 'fully_connected_param_pb2'
  # @@protoc_insertion_point(class_scope:XZY_FullyConnectedParam)
  ))
_sym_db.RegisterMessage(XZY_FullyConnectedParam)


# @@protoc_insertion_point(module_scope)
