# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: max_pooling_param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto_py.size_pb2 as size__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='max_pooling_param.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17max_pooling_param.proto\x1a\nsize.proto\"l\n\x13XZY_MaxPoolingParam\x12\"\n\x0f\x63ol_matrix_size\x18\x01 \x01(\x0b\x32\t.XZY_Size\x12\x1e\n\x0bkernel_size\x18\x02 \x01(\x0b\x32\t.XZY_Size\x12\x11\n\tcol_table\x18\x03 \x03(\x05\x62\x06proto3')
  ,
  dependencies=[size__pb2.DESCRIPTOR,])




_XZY_MAXPOOLINGPARAM = _descriptor.Descriptor(
  name='XZY_MaxPoolingParam',
  full_name='XZY_MaxPoolingParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col_matrix_size', full_name='XZY_MaxPoolingParam.col_matrix_size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_size', full_name='XZY_MaxPoolingParam.kernel_size', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='col_table', full_name='XZY_MaxPoolingParam.col_table', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=147,
)

_XZY_MAXPOOLINGPARAM.fields_by_name['col_matrix_size'].message_type = size__pb2._XZY_SIZE
_XZY_MAXPOOLINGPARAM.fields_by_name['kernel_size'].message_type = size__pb2._XZY_SIZE
DESCRIPTOR.message_types_by_name['XZY_MaxPoolingParam'] = _XZY_MAXPOOLINGPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XZY_MaxPoolingParam = _reflection.GeneratedProtocolMessageType('XZY_MaxPoolingParam', (_message.Message,), dict(
  DESCRIPTOR = _XZY_MAXPOOLINGPARAM,
  __module__ = 'max_pooling_param_pb2'
  # @@protoc_insertion_point(class_scope:XZY_MaxPoolingParam)
  ))
_sym_db.RegisterMessage(XZY_MaxPoolingParam)


# @@protoc_insertion_point(module_scope)
