# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto_py.node_pb2 as node__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='network.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rnetwork.proto\x1a\nnode.proto\"1\n\x0bXZY_Network\x12\"\n\x0foperation_nodes\x18\x02 \x03(\x0b\x32\t.XZY_Nodeb\x06proto3')
  ,
  dependencies=[node__pb2.DESCRIPTOR,])




_XZY_NETWORK = _descriptor.Descriptor(
  name='XZY_Network',
  full_name='XZY_Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_nodes', full_name='XZY_Network.operation_nodes', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=78,
)

_XZY_NETWORK.fields_by_name['operation_nodes'].message_type = node__pb2._XZY_NODE
DESCRIPTOR.message_types_by_name['XZY_Network'] = _XZY_NETWORK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XZY_Network = _reflection.GeneratedProtocolMessageType('XZY_Network', (_message.Message,), dict(
  DESCRIPTOR = _XZY_NETWORK,
  __module__ = 'network_pb2'
  # @@protoc_insertion_point(class_scope:XZY_Network)
  ))
_sym_db.RegisterMessage(XZY_Network)


# @@protoc_insertion_point(module_scope)
