# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto_py.shape_pb2 as shape__pb2
import proto_py.batch_norm_param_pb2 as batch__norm__param__pb2
import proto_py.conv_param_pb2 as conv__param__pb2
import proto_py.fully_connected_param_pb2 as fully__connected__param__pb2
import proto_py.max_pooling_param_pb2 as max__pooling__param__pb2
import proto_py.separable_convolution_param_pb2 as separable__convolution__param__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='node.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nnode.proto\x1a\x0bshape.proto\x1a\x16\x62\x61tch_norm_param.proto\x1a\x10\x63onv_param.proto\x1a\x1b\x66ully_connected_param.proto\x1a\x17max_pooling_param.proto\x1a!separable_convolution_param.proto\"\xa7\x03\n\x08XZY_Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0binput_names\x18\x02 \x03(\t\x12 \n\x0cinput_shapes\x18\x03 \x03(\x0b\x32\n.XZY_Shape\x12 \n\x0coutput_shape\x18\x04 \x01(\x0b\x32\n.XZY_Shape\x12\x41\n\x19\x62\x61tch_normalization_param\x18\x05 \x01(\x0b\x32\x1c.XZY_BatchNormalizationParamH\x00\x12\x32\n\x11\x63onvolution_param\x18\x06 \x01(\x0b\x32\x15.XZY_ConvolutionParamH\x00\x12\x39\n\x15\x66ully_connected_param\x18\x07 \x01(\x0b\x32\x18.XZY_FullyConnectedParamH\x00\x12\x31\n\x11max_pooling_param\x18\x08 \x01(\x0b\x32\x14.XZY_MaxPoolingParamH\x00\x12\x46\n\x1bseparable_convolution_param\x18\t \x01(\x0b\x32\x1f.XZY_SeparableConvolutionParamsH\x00\x42\x07\n\x05paramb\x06proto3')
  ,
  dependencies=[shape__pb2.DESCRIPTOR,batch__norm__param__pb2.DESCRIPTOR,conv__param__pb2.DESCRIPTOR,fully__connected__param__pb2.DESCRIPTOR,max__pooling__param__pb2.DESCRIPTOR,separable__convolution__param__pb2.DESCRIPTOR,])




_XZY_NODE = _descriptor.Descriptor(
  name='XZY_Node',
  full_name='XZY_Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='XZY_Node.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_names', full_name='XZY_Node.input_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_shapes', full_name='XZY_Node.input_shapes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_shape', full_name='XZY_Node.output_shape', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_normalization_param', full_name='XZY_Node.batch_normalization_param', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='convolution_param', full_name='XZY_Node.convolution_param', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fully_connected_param', full_name='XZY_Node.fully_connected_param', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_pooling_param', full_name='XZY_Node.max_pooling_param', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='separable_convolution_param', full_name='XZY_Node.separable_convolution_param', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='param', full_name='XZY_Node.param',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=159,
  serialized_end=582,
)

_XZY_NODE.fields_by_name['input_shapes'].message_type = shape__pb2._XZY_SHAPE
_XZY_NODE.fields_by_name['output_shape'].message_type = shape__pb2._XZY_SHAPE
_XZY_NODE.fields_by_name['batch_normalization_param'].message_type = batch__norm__param__pb2._XZY_BATCHNORMALIZATIONPARAM
_XZY_NODE.fields_by_name['convolution_param'].message_type = conv__param__pb2._XZY_CONVOLUTIONPARAM
_XZY_NODE.fields_by_name['fully_connected_param'].message_type = fully__connected__param__pb2._XZY_FULLYCONNECTEDPARAM
_XZY_NODE.fields_by_name['max_pooling_param'].message_type = max__pooling__param__pb2._XZY_MAXPOOLINGPARAM
_XZY_NODE.fields_by_name['separable_convolution_param'].message_type = separable__convolution__param__pb2._XZY_SEPARABLECONVOLUTIONPARAMS
_XZY_NODE.oneofs_by_name['param'].fields.append(
  _XZY_NODE.fields_by_name['batch_normalization_param'])
_XZY_NODE.fields_by_name['batch_normalization_param'].containing_oneof = _XZY_NODE.oneofs_by_name['param']
_XZY_NODE.oneofs_by_name['param'].fields.append(
  _XZY_NODE.fields_by_name['convolution_param'])
_XZY_NODE.fields_by_name['convolution_param'].containing_oneof = _XZY_NODE.oneofs_by_name['param']
_XZY_NODE.oneofs_by_name['param'].fields.append(
  _XZY_NODE.fields_by_name['fully_connected_param'])
_XZY_NODE.fields_by_name['fully_connected_param'].containing_oneof = _XZY_NODE.oneofs_by_name['param']
_XZY_NODE.oneofs_by_name['param'].fields.append(
  _XZY_NODE.fields_by_name['max_pooling_param'])
_XZY_NODE.fields_by_name['max_pooling_param'].containing_oneof = _XZY_NODE.oneofs_by_name['param']
_XZY_NODE.oneofs_by_name['param'].fields.append(
  _XZY_NODE.fields_by_name['separable_convolution_param'])
_XZY_NODE.fields_by_name['separable_convolution_param'].containing_oneof = _XZY_NODE.oneofs_by_name['param']
DESCRIPTOR.message_types_by_name['XZY_Node'] = _XZY_NODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XZY_Node = _reflection.GeneratedProtocolMessageType('XZY_Node', (_message.Message,), dict(
  DESCRIPTOR = _XZY_NODE,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:XZY_Node)
  ))
_sym_db.RegisterMessage(XZY_Node)


# @@protoc_insertion_point(module_scope)
