# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shape.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shape.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bshape.proto\";\n\tXZY_Shape\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\rb\x06proto3')
)




_XZY_SHAPE = _descriptor.Descriptor(
  name='XZY_Shape',
  full_name='XZY_Shape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='XZY_Shape.channel', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='XZY_Shape.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='XZY_Shape.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['XZY_Shape'] = _XZY_SHAPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XZY_Shape = _reflection.GeneratedProtocolMessageType('XZY_Shape', (_message.Message,), dict(
  DESCRIPTOR = _XZY_SHAPE,
  __module__ = 'shape_pb2'
  # @@protoc_insertion_point(class_scope:XZY_Shape)
  ))
_sym_db.RegisterMessage(XZY_Shape)


# @@protoc_insertion_point(module_scope)
