from network_factory.layer_name import Conv, MaxPool, DepthSepConv, SE_Module, Res_Add
CONV_DEFS = [
    # Conv(kernel=[3, 3], stride=1, depth=32),
    DepthSepConv(kernel=[3, 3], stride=1, depth=32),
    MaxPool(kernel=[2, 2], stride=2),

    # Conv(kernel=[3, 3], stride=1, depth=64),
    DepthSepConv(kernel=[3, 3], stride=1, depth=64),
    # SE_Module(stride=1),
    # Res_Add(inputs1="MaxPool_1", inputs2="SE_Module_1", stride=1),
    MaxPool(kernel=[2, 2], stride=2),

    DepthSepConv(kernel=[3, 3], stride=1, depth=128),
    SE_Module(stride=1),
    Conv(kernel=[1, 1], stride=1, depth=32),
    DepthSepConv(kernel=[3, 3], stride=1, depth=128),
    SE_Module(stride=1),
    Res_Add(inputs1="MaxPool_2", inputs2="SE_Module_2", stride=1),
    MaxPool(kernel=[2, 2], stride=2),

    DepthSepConv(kernel=[3, 3], stride=1, depth=256),
    SE_Module(stride=1),
    Conv(kernel=[1, 1], stride=1, depth=64),
    DepthSepConv(kernel=[3, 3], stride=1, depth=256),
    SE_Module(stride=1),
    Res_Add(inputs1="MaxPool_3", inputs2="SE_Module_4", stride=1),
    # Res_Add(inputs1="MaxPool_3", inputs2="DepthSepConv_4", stride=1),
    MaxPool(kernel=[2, 2], stride=2),

    DepthSepConv(kernel=[3, 3], stride=1, depth=512),
    SE_Module(stride=1),
    Conv(kernel=[1, 1], stride=1, depth=128),
    DepthSepConv(kernel=[3, 3], stride=1, depth=512),
    SE_Module(stride=1),
    Res_Add(inputs1="MaxPool_4", inputs2="SE_Module_6", stride=1),
    Conv(kernel=[1, 1], stride=1, depth=128),
    DepthSepConv(kernel=[3, 3], stride=1, depth=512),
    # SE_Module(stride=1),
    # MaxPool(kernel=[2, 2], stride=2),
    #
    # DepthSepConv(kernel=[3, 3], stride=1, depth=1024),
    # SE_Module(stride=1),
    # Conv(kernel=[1, 1], stride=1, depth=512),
    # DepthSepConv(kernel=[3, 3], stride=1, depth=1024),
    # SE_Module(stride=1),
    # Res_Add(inputs1="MaxPool_5", inputs2="SE_Module_10", stride=1),
    # Conv(kernel=[1, 1], stride=1, depth=512),
    # DepthSepConv(kernel=[3, 3], stride=1, depth=1024),
    # SE_Module(stride=1),
]
